# Generated by Django 4.2.30 on 2026-08-30 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
        migrations.CreateModel(
            name='ClientEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_intervention', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name="Note de l'intervention (/5)")),
                ('note_technicien', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Note du technicien (/100)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_client', to='core.intervention', verbose_name='Intervention')),
            ],
            options={
                'verbose_name': 'Évaluation client',
                'verbose_name_plural': 'Évaluations clients',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
