# Generated by Django 4.2.30 on 2026-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_report_options_clientevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='derniere_position_maj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière position à'),
        ),
    ]